import React,{useEffect,useRef,useState}from'react';
import{ActivityIndicator,Alert,Animated,KeyboardAvoidingView,Linking,NativeModules,Platform,Pressable,SafeAreaView,ScrollView,Share,StatusBar,StyleSheet,Text,TextInput,View}from'react-native';
import{calculateChart,type Chart}from'./astrology';

const{AstroNative}=NativeModules,PRICE=49,UPI_ID='';
type L='en'|'hi'|'or';
type Screen='home'|'birth'|'chart'|'premium'|'settings';
type Boot={deviceId:string;loggedIn:boolean;name?:string;email?:string;premium:boolean;birthProfile?:string};
type Birth={date:string;time:string;place:string;latitude:string;longitude:string;tz:string};

const C={
 en:{login:'Login',register:'Create account',name:'Full name',email:'Email',password:'Password',confirm:'Confirm password',go:'Continue',hello:'Namaste',sub:'Deterministic Vedic astrology, calculated privately on your phone.',kundli:'Create Kundli',chart:'My Chart',premium:'Premium Insights',settings:'Settings',birth:'Birth Details',help:'Exact birth time matters. Use accurate coordinates and UTC offset.',date:'Birth date (YYYY-MM-DD)',time:'Birth time (HH:MM)',place:'Birth place',lat:'Latitude',lon:'Longitude',tz:'UTC offset minutes',calc:'Calculate Kundli',lagna:'Lagna',panchang:'Panchang',planets:'Planetary Positions',dasha:'Current Mahadasha',pay:'Pay ₹49 by UPI',setup:'UPI is not configured yet. Payment is disabled until the owner adds the receiving UPI ID.',utr:'UTR / Transaction ID',share:'Share verification request',device:'Device ID',code:'Activation code',activate:'Activate Premium',active:'Premium Active',privacy:'Local account and birth profile are encrypted using Android Keystore-backed storage.',logout:'Logout',back:'Back',no:'Create a Kundli first.',disc:'Astrology is traditional guidance and is not scientifically established. Do not use it as medical, legal or financial advice.'},
 hi:{login:'लॉग इन',register:'खाता बनाएँ',name:'पूरा नाम',email:'ईमेल',password:'पासवर्ड',confirm:'पासवर्ड दोबारा लिखें',go:'आगे बढ़ें',hello:'नमस्ते',sub:'आपके फ़ोन पर निजी और निश्चित वैदिक ज्योतिष गणना।',kundli:'कुंडली बनाएँ',chart:'मेरी कुंडली',premium:'प्रीमियम',settings:'सेटिंग्स',birth:'जन्म विवरण',help:'सटीक जन्म समय महत्वपूर्ण है। सही coordinates और UTC offset दें।',date:'जन्म तिथि (YYYY-MM-DD)',time:'जन्म समय (HH:MM)',place:'जन्म स्थान',lat:'अक्षांश',lon:'देशांतर',tz:'UTC offset minutes',calc:'कुंडली गणना करें',lagna:'लग्न',panchang:'पंचांग',planets:'ग्रह स्थिति',dasha:'वर्तमान महादशा',pay:'UPI से ₹49 भुगतान',setup:'UPI अभी कॉन्फ़िगर नहीं है। मालिक के UPI ID जोड़ने तक भुगतान बंद है।',utr:'UTR / Transaction ID',share:'सत्यापन अनुरोध शेयर करें',device:'डिवाइस ID',code:'एक्टिवेशन कोड',activate:'प्रीमियम सक्रिय करें',active:'प्रीमियम सक्रिय',privacy:'स्थानीय खाता और जन्म विवरण Android Keystore आधारित एन्क्रिप्शन से सुरक्षित हैं।',logout:'लॉग आउट',back:'वापस',no:'पहले कुंडली बनाएँ।',disc:'ज्योतिष पारंपरिक मार्गदर्शन है और वैज्ञानिक रूप से स्थापित नहीं है। चिकित्सा, कानूनी या वित्तीय सलाह के स्थान पर इसका उपयोग न करें।'},
 or:{login:'ଲଗ୍ ଇନ୍',register:'ଆକାଉଣ୍ଟ ତିଆରି',name:'ପୂର୍ଣ୍ଣ ନାମ',email:'ଇମେଲ୍',password:'ପାସୱାର୍ଡ',confirm:'ପାସୱାର୍ଡ ପୁଣି ଲେଖନ୍ତୁ',go:'ଆଗକୁ',hello:'ନମସ୍କାର',sub:'ଆପଣଙ୍କ ଫୋନ୍‌ରେ ବ୍ୟକ୍ତିଗତ ଓ ନିର୍ଦ୍ଧାରିତ ବୈଦିକ ଜ୍ୟୋତିଷ ଗଣନା।',kundli:'କୁଣ୍ଡଳୀ ତିଆରି',chart:'ମୋ କୁଣ୍ଡଳୀ',premium:'ପ୍ରିମିୟମ୍',settings:'ସେଟିଂସ୍',birth:'ଜନ୍ମ ବିବରଣୀ',help:'ସଠିକ୍ ଜନ୍ମ ସମୟ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ। ସଠିକ୍ coordinates ଓ UTC offset ଦିଅନ୍ତୁ।',date:'ଜନ୍ମ ତାରିଖ (YYYY-MM-DD)',time:'ଜନ୍ମ ସମୟ (HH:MM)',place:'ଜନ୍ମ ସ୍ଥାନ',lat:'Latitude',lon:'Longitude',tz:'UTC offset minutes',calc:'କୁଣ୍ଡଳୀ ଗଣନା',lagna:'ଲଗ୍ନ',panchang:'ପଞ୍ଚାଙ୍ଗ',planets:'ଗ୍ରହ ସ୍ଥିତି',dasha:'ବର୍ତ୍ତମାନ ମହାଦଶା',pay:'UPI ଦ୍ୱାରା ₹49 ପେମେଣ୍ଟ',setup:'UPI ଏପର୍ଯ୍ୟନ୍ତ ସେଟ୍ ହୋଇନାହିଁ। ମାଲିକଙ୍କ UPI ID ଯୋଡ଼ାଯାଏ ପର୍ଯ୍ୟନ୍ତ ପେମେଣ୍ଟ ବନ୍ଦ।',utr:'UTR / Transaction ID',share:'ଯାଞ୍ଚ ଅନୁରୋଧ ଶେୟର୍',device:'ଡିଭାଇସ୍ ID',code:'ଆକ୍ଟିଭେସନ୍ କୋଡ୍',activate:'ପ୍ରିମିୟମ୍ ସକ୍ରିୟ',active:'ପ୍ରିମିୟମ୍ ସକ୍ରିୟ',privacy:'Local account ଓ birth profile Android Keystore ଭିତ୍ତିକ encryption ଦ୍ୱାରା ସୁରକ୍ଷିତ।',logout:'ଲଗ୍ ଆଉଟ୍',back:'ପଛକୁ',no:'ପ୍ରଥମେ କୁଣ୍ଡଳୀ ତିଆରି କରନ୍ତୁ।',disc:'ଜ୍ୟୋତିଷ ପାରମ୍ପରିକ ମାର୍ଗଦର୍ଶନ ଓ ବୈଜ୍ଞାନିକ ଭାବେ ସ୍ଥାପିତ ନୁହେଁ। medical, legal କିମ୍ବା financial advice ର ବଦଳରେ ବ୍ୟବହାର କରନ୍ତୁ ନାହିଁ।'}
}as const;

const cities=[['Bhubaneswar','20.2961','85.8245','330'],['Cuttack','20.4625','85.8830','330'],['Puri','19.8135','85.8312','330'],['Delhi','28.6139','77.2090','330'],['Mumbai','19.0760','72.8777','330'],['Bengaluru','12.9716','77.5946','330']];
const EMPTY:Birth={date:'',time:'',place:'Bhubaneswar',latitude:'20.2961',longitude:'85.8245',tz:'330'};

export default function App(){
 const[l,setL]=useState<L>('en'),[boot,setBoot]=useState<Boot|null>(null),[mode,setMode]=useState<'login'|'register'>('login'),[screen,setScreen]=useState<Screen>('home'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[birth,setBirth]=useState<Birth>(EMPTY),[chart,setChart]=useState<Chart>(),[utr,setUtr]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),pulse=useRef(new Animated.Value(.55)).current,t=C[l];
 useEffect(()=>{Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:1600,useNativeDriver:true}),Animated.timing(pulse,{toValue:.55,duration:1600,useNativeDriver:true})])).start();load()},[]);
 async function load(){try{const b=await AstroNative.getBootstrap();setBoot(b);if(b.birthProfile)setBirth(JSON.parse(b.birthProfile))}catch(e:any){Alert.alert('AstroSathi',e?.message||String(e))}}
 async function auth(){
  const mail=email.trim();
  if(!mail||!mail.includes('@'))return Alert.alert('AstroSathi','Please enter a valid email address.');
  if(password.length<6)return Alert.alert('AstroSathi','Password must contain at least 6 characters.');
  if(mode==='register'&&name.trim().length<2)return Alert.alert('AstroSathi','Please enter your full name.');
  if(mode==='register'&&password!==confirm)return Alert.alert('AstroSathi','Passwords do not match.');
  setBusy(true);try{mode==='register'?await AstroNative.register(name.trim(),mail,password):await AstroNative.login(mail,password);await load()}catch(e:any){Alert.alert('AstroSathi',e?.message||String(e))}finally{setBusy(false)}
 }
 async function calculate(){setBusy(true);try{await AstroNative.saveBirthProfile(JSON.stringify(birth));setChart(calculateChart(birth.date,birth.time,+birth.latitude,+birth.longitude,+birth.tz));setScreen('chart');await load()}catch(e:any){Alert.alert('AstroSathi',e?.message||String(e))}finally{setBusy(false)}}
 async function pay(){if(!UPI_ID)return Alert.alert('AstroSathi',t.setup);await Linking.openURL(`upi://pay?pa=${encodeURIComponent(UPI_ID)}&pn=AstroSathi&am=${PRICE}&cu=INR&tn=AstroSathi%20Full%20Report`)}
 async function activate(){setBusy(true);try{await AstroNative.verifyActivation(code);await load();Alert.alert(t.active)}catch(e:any){Alert.alert('AstroSathi',e?.message||String(e))}finally{setBusy(false)}}
 if(!boot)return<Shell><ActivityIndicator color="#f2d17b" size="large"/></Shell>;
 if(!boot.loggedIn)return<Shell><KeyboardAvoidingView style={s.keyboard} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={s.authScroll}><View style={s.auth}><Orb pulse={pulse}/><Text style={s.logoBig}>AstroSathi</Text><View style={s.langCenter}><Lang l={l} setL={setL}/></View><View style={s.formCard}><Text style={s.authTitle}>{mode==='login'?t.login:t.register}</Text>{mode==='register'&&<Field label={t.name} value={name} onChangeText={setName} autoCapitalize="words" returnKeyType="next"/>}<Field label={t.email} value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address" returnKeyType="next"/><Field label={t.password} value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" returnKeyType={mode==='register'?'next':'done'}/>{mode==='register'&&<Field label={t.confirm} value={confirm} onChangeText={setConfirm} secureTextEntry autoCapitalize="none" returnKeyType="done"/>}<Btn onPress={auth}>{busy?'…':t.go}</Btn></View><Pressable hitSlop={12} onPress={()=>{setMode(mode==='login'?'register':'login');setPassword('');setConfirm('')}}><Text style={s.link}>{mode==='login'?t.register:t.login}</Text></Pressable></View></ScrollView></KeyboardAvoidingView></Shell>;
 return<Shell><View style={s.head}><Pressable onPress={()=>setScreen('home')}><Text style={s.logo}>✦ AstroSathi</Text></Pressable><Lang l={l} setL={setL}/></View>{screen==='home'&&<ScrollView contentContainerStyle={s.page}><View style={s.hero}><Text style={s.kicker}>{t.hello}{boot.name?`, ${boot.name}`:''}</Text><Text style={s.heroTitle}>Read the sky{`\n`}within you.</Text><Text style={s.muted}>{t.sub}</Text><Orb pulse={pulse}/></View><Tile icon="☸" title={t.kundli} onPress={()=>setScreen('birth')}/><View style={s.row}><Tile icon="☾" title={t.chart} onPress={()=>setScreen('chart')} small/><Tile icon="✦" title={boot.premium?t.active:t.premium} onPress={()=>setScreen('premium')} small/></View><Tile icon="⚙" title={t.settings} onPress={()=>setScreen('settings')}/><Text style={s.disc}>{t.disc}</Text></ScrollView>}{screen==='birth'&&<BirthView birth={birth} setBirth={setBirth} t={t} calc={calculate} busy={busy} back={()=>setScreen('home')}/>} {screen==='chart'&&<ChartView chart={chart} t={t} back={()=>setScreen('home')}/>} {screen==='premium'&&<ScrollView contentContainerStyle={s.page}><Back t={t} go={()=>setScreen('home')}/><Text style={s.title}>{boot.premium?t.active:t.premium}</Text>{boot.premium?<Card><Text style={s.good}>✓ {t.active}</Text></Card>:<><Card><Text style={s.price}>₹{PRICE}</Text><Text style={s.muted}>{t.setup}</Text><Btn onPress={pay}>{t.pay}</Btn></Card><Field label={t.utr} value={utr} onChangeText={setUtr}/><Field label={t.device} value={boot.deviceId} editable={false}/><Btn secondary onPress={()=>Share.share({message:`AstroSathi verification\nAmount: ₹${PRICE}\nUTR: ${utr}\nDevice ID: ${boot.deviceId}`})}>{t.share}</Btn><Field label={t.code} value={code} onChangeText={setCode} multiline/><Btn onPress={activate}>{busy?'…':t.activate}</Btn></>}</ScrollView>} {screen==='settings'&&<ScrollView contentContainerStyle={s.page}><Back t={t} go={()=>setScreen('home')}/><Text style={s.title}>{t.settings}</Text><Card><Text style={s.cardTitle}>{boot.name}</Text><Text style={s.muted}>{boot.email}</Text></Card><Card><Text style={s.muted}>{t.privacy}</Text></Card><Btn secondary onPress={async()=>{await AstroNative.logout();setChart(undefined);setScreen('home');await load()}}>{t.logout}</Btn></ScrollView>}</Shell>
}

function BirthView({birth,setBirth,t,calc,busy,back}:any){const set=(k:string)=>(v:string)=>setBirth({...birth,[k]:v});return<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><Back t={t} go={back}/><Text style={s.title}>{t.birth}</Text><Text style={s.muted}>{t.help}</Text><Field label={t.date} value={birth.date} onChangeText={set('date')} placeholder="1995-06-15"/><Field label={t.time} value={birth.time} onChangeText={set('time')} placeholder="08:30"/><Field label={t.place} value={birth.place} onChangeText={set('place')}/><View style={s.row}><Field containerStyle={s.flexField} label={t.lat} value={birth.latitude} onChangeText={set('latitude')}/><Field containerStyle={s.flexField} label={t.lon} value={birth.longitude} onChangeText={set('longitude')}/></View><Field label={t.tz} value={birth.tz} onChangeText={set('tz')}/><View style={s.chips}>{cities.map(c=><Pressable key={c[0]} style={s.chip} onPress={()=>setBirth({...birth,place:c[0],latitude:c[1],longitude:c[2],tz:c[3]})}><Text style={s.chipText}>{c[0]}</Text></Pressable>)}</View><Btn onPress={calc}>{busy?'Calculating…':t.calc}</Btn></ScrollView>}

function ChartView({chart,t,back}:{chart?:Chart;t:any;back:()=>void}){if(!chart)return<ScrollView contentContainerStyle={s.page}><Back t={t} go={back}/><Text style={s.title}>{t.no}</Text></ScrollView>;return<ScrollView contentContainerStyle={s.page}><Back t={t} go={back}/><Text style={s.kicker}>VEDIC CHART</Text><Text style={s.heroTitle}>{chart.ascendant.rashi} {t.lagna}</Text><View style={s.row}><Metric k={t.lagna} v={`${chart.ascendant.rashi} ${chart.ascendant.degreesInRashi.toFixed(2)}°`} x={`${chart.ascendant.nakshatra} • Pada ${chart.ascendant.pada}`}/><Metric k={t.dasha} v={chart.dasha.currentLord} x={new Date(chart.dasha.currentEndsAt).toLocaleDateString()}/></View><Card><Text style={s.gold}>{t.panchang}</Text><Text style={s.cardTitle}>{chart.panchang.paksha} • {chart.panchang.tithi}</Text><Text style={s.muted}>{chart.panchang.nakshatra} Pada {chart.panchang.pada} · {chart.panchang.yoga} · {chart.panchang.karana}</Text></Card><Card><Text style={s.gold}>{t.planets}</Text>{chart.planets.map(p=><View style={s.planet} key={p.name}><View><Text style={s.white}>{p.name}{p.retrograde?' R':''}</Text><Text style={s.small}>{p.nakshatra} P{p.pada}</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.white}>{p.rashi} {p.degreesInRashi.toFixed(2)}°</Text><Text style={s.small}>H{p.house} · D9 {p.navamsa}</Text></View></View>)}</Card><Card><Text style={s.gold}>CALCULATION STANDARD</Text><Text style={s.muted}>{chart.ephemeris} · Lahiri/IAE true ayanamsha · mean nodes · whole-sign houses.</Text><Text style={s.small}>Ayanamsha {chart.ayanamsaDegrees.toFixed(6)}° · {chart.utc}</Text></Card><Text style={s.disc}>{t.disc}</Text></ScrollView>}

const Shell=({children}:{children:React.ReactNode})=><SafeAreaView style={s.safe}><StatusBar barStyle="light-content" backgroundColor="#080511"/>{children}</SafeAreaView>;
const Orb=({pulse}:{pulse:Animated.Value})=><Animated.View style={[s.orb,{opacity:pulse,transform:[{scale:pulse.interpolate({inputRange:[.55,1],outputRange:[.93,1.05]})}]}]}><Text style={s.sun}>☉</Text></Animated.View>;
const Lang=({l,setL}:{l:L;setL:(x:L)=>void})=><View style={s.lang}>{(['en','hi','or']as L[]).map(x=><Pressable key={x} onPress={()=>setL(x)} style={[s.langBtn,l===x&&s.langOn]}><Text style={[s.langText,l===x&&{color:'#251606'}]}>{x==='en'?'EN':x==='hi'?'हिं':'ଓଡ଼ିଆ'}</Text></Pressable>)}</View>;
function Field({label,containerStyle,multiline,...p}:any){return<View style={[s.fieldWrap,containerStyle]}><Text style={s.label}>{label}</Text><TextInput {...p} multiline={multiline} placeholderTextColor="#756b83" selectionColor="#f2d17b" style={[s.input,multiline&&s.inputMulti]}/></View>}
const Btn=({children,onPress,secondary}:any)=><Pressable onPress={onPress} style={({pressed})=>[s.btn,secondary&&s.btn2,pressed&&{opacity:.86}]}><Text style={[s.btnText,secondary&&{color:'#f2d17b'}]}>{children}</Text></Pressable>;
const Tile=({icon,title,onPress,small}:any)=><Pressable onPress={onPress} style={[s.tile,small&&{flex:1,minHeight:110}]}><Text style={s.icon}>{icon}</Text><Text style={s.tileText}>{title}</Text><Text style={s.chev}>›</Text></Pressable>;
const Card=({children}:{children:React.ReactNode})=><View style={s.card}>{children}</View>;
const Back=({t,go}:any)=><Pressable onPress={go}><Text style={s.back}>‹ {t.back}</Text></Pressable>;
const Metric=({k,v,x}:any)=><View style={s.metric}><Text style={s.small}>{k}</Text><Text style={s.cardTitle}>{v}</Text><Text style={s.small}>{x}</Text></View>;

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:'#080511'},keyboard:{flex:1},head:{height:62,paddingHorizontal:18,borderBottomWidth:1,borderBottomColor:'#251a34',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},page:{padding:20,paddingBottom:55,gap:13},
 authScroll:{flexGrow:1,justifyContent:'center',paddingHorizontal:24,paddingVertical:32},auth:{width:'100%',maxWidth:520,alignSelf:'center'},logo:{color:'#f2d17b',fontWeight:'900',fontSize:18},logoBig:{color:'#fff8e8',fontSize:42,lineHeight:48,fontWeight:'900',letterSpacing:-1.8,textAlign:'center',marginTop:16},langCenter:{alignItems:'center',marginTop:14},formCard:{width:'100%',marginTop:26,borderWidth:1,borderColor:'#342447',backgroundColor:'#100a1a',borderRadius:24,padding:18,gap:15},authTitle:{color:'#fff8e8',fontWeight:'900',fontSize:22,marginBottom:2},
 hero:{padding:23,borderWidth:1,borderColor:'#38254d',backgroundColor:'#120c20',borderRadius:28,minHeight:280},kicker:{color:'#f2d17b',fontWeight:'900',fontSize:11,letterSpacing:1.4},heroTitle:{color:'#fff8e8',fontSize:38,lineHeight:41,fontWeight:'900',letterSpacing:-1.7,marginVertical:9},title:{color:'#fff8e8',fontSize:31,fontWeight:'900',letterSpacing:-1},muted:{color:'#a096ac',lineHeight:20},small:{color:'#786e85',fontSize:11,lineHeight:15},
 orb:{width:105,height:105,borderRadius:53,backgroundColor:'#281541',borderWidth:1,borderColor:'#77549d',alignItems:'center',justifyContent:'center',alignSelf:'center',marginTop:8,elevation:8},sun:{fontSize:52,color:'#f2d17b'},row:{flexDirection:'row',gap:11,alignItems:'flex-start'},tile:{borderWidth:1,borderColor:'#302142',backgroundColor:'#110b1b',borderRadius:20,padding:17,flexDirection:'row',alignItems:'center',gap:12},icon:{fontSize:26,color:'#f2d17b'},tileText:{color:'#fff8e8',fontWeight:'800',flex:1},chev:{fontSize:27,color:'#6f617d'},
 lang:{flexDirection:'row',gap:6},langBtn:{borderWidth:1,borderColor:'#382747',paddingHorizontal:11,paddingVertical:7,borderRadius:999,minHeight:34,justifyContent:'center'},langOn:{backgroundColor:'#f2d17b',borderColor:'#f2d17b'},langText:{color:'#b5a8c2',fontSize:11,fontWeight:'900'},
 fieldWrap:{width:'100%',minWidth:0},flexField:{flex:1,width:undefined},label:{color:'#b7a9c3',fontSize:11,fontWeight:'800',marginBottom:7,textTransform:'uppercase'},input:{width:'100%',height:56,borderWidth:1,borderColor:'#48325f',borderRadius:15,backgroundColor:'#0b0712',color:'#fff8e8',paddingHorizontal:15,paddingVertical:0,fontSize:16},inputMulti:{height:100,minHeight:100,paddingTop:14,textAlignVertical:'top'},
 btn:{width:'100%',minHeight:56,borderRadius:16,backgroundColor:'#f2d17b',alignItems:'center',justifyContent:'center',paddingHorizontal:16,paddingVertical:12,marginTop:2},btn2:{backgroundColor:'#161021',borderWidth:1,borderColor:'#57406e'},btnText:{fontWeight:'900',fontSize:16,color:'#241606'},link:{color:'#ceb4e8',textAlign:'center',paddingVertical:17,fontWeight:'800',fontSize:16},
 card:{borderWidth:1,borderColor:'#302142',borderRadius:20,backgroundColor:'#110b1b',padding:17,gap:8},cardTitle:{color:'#fff8e8',fontSize:17,fontWeight:'800'},gold:{color:'#f2d17b',fontWeight:'900',fontSize:11,letterSpacing:1},white:{color:'#fff8e8',fontWeight:'700'},planet:{flexDirection:'row',justifyContent:'space-between',paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#21172e'},metric:{flex:1,minHeight:118,borderWidth:1,borderColor:'#302142',backgroundColor:'#110b1b',borderRadius:19,padding:14,gap:6},price:{color:'#f2d17b',fontWeight:'900',fontSize:45},good:{color:'#89e5a7',fontSize:22,fontWeight:'900'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#362449',backgroundColor:'#171021',borderRadius:999,paddingHorizontal:11,paddingVertical:8},chipText:{color:'#c9b7dc',fontSize:11,fontWeight:'700'},back:{color:'#c5afdc',fontWeight:'700'},disc:{color:'#665d71',fontSize:10,lineHeight:16,textAlign:'center',marginTop:8}
});
