import * as Astronomy from 'astronomy-engine';

export type Planet={name:string;siderealLongitude:number;rashi:string;degreesInRashi:number;nakshatra:string;pada:number;house:number;navamsa:string;retrograde:boolean};
export type Chart={engineVersion:string;ephemeris:string;ayanamsa:string;ayanamsaDegrees:number;utc:string;ascendant:{longitude:number;rashi:string;degreesInRashi:number;nakshatra:string;pada:number};planets:Planet[];panchang:{tithiNumber:number;tithi:string;paksha:string;nakshatra:string;pada:number;yoga:string;karana:string};dasha:{birthLord:string;currentLord:string;currentEndsAt:number;periods:Array<{lord:string;startsAt:number;endsAt:number}>}};
const RASHIS=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'] as const;
const NAKSHATRAS=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'] as const;
const YOGAS=['Vishkambha','Priti','Ayushman','Saubhagya','Shobhana','Atiganda','Sukarma','Dhriti','Shula','Ganda','Vriddhi','Dhruva','Vyaghata','Harshana','Vajra','Siddhi','Vyatipata','Variyana','Parigha','Shiva','Siddha','Sadhya','Shubha','Shukla','Brahma','Indra','Vaidhriti'] as const;
const TITHIS=['Pratipada','Dwitiya','Tritiya','Chaturthi','Panchami','Shashthi','Saptami','Ashtami','Navami','Dashami','Ekadashi','Dwadashi','Trayodashi','Chaturdashi'] as const;
const ORDER=['Ketu','Venus','Sun','Moon','Mars','Rahu','Jupiter','Saturn','Mercury'] as const, YEARS:Record<string,number>={Ketu:7,Venus:20,Sun:6,Moon:10,Mars:7,Rahu:18,Jupiter:16,Saturn:19,Mercury:17};
const NS=360/27,PS=NS/4,DAY=86400000,D=Math.PI/180,R=180/Math.PI;
const n360=(v:number)=>((v%360)+360)%360; const n180=(v:number)=>{const x=n360(v);return x>=180?x-360:x};
const jd=(d:Date)=>d.getTime()/DAY+2440587.5; const T=(d:Date)=>(jd(d)-2451545)/36525;
function nut(d:Date){const t=T(d),l=n360(280.4665+36000.7698*t)*D,lp=n360(218.3165+481267.8813*t)*D,o=n360(125.04452-1934.136261*t)*D;return{p:-17.20*Math.sin(o)-1.32*Math.sin(2*l)-.23*Math.sin(2*lp)+.21*Math.sin(2*o),e:9.20*Math.cos(o)+.57*Math.cos(2*l)+.10*Math.cos(2*lp)-.09*Math.cos(2*o)}}
function obl(d:Date){const t=T(d);return(84381.406-46.836769*t-.0001831*t*t+.00200340*t**3-5.76e-7*t**4-4.34e-8*t**5)/3600}
function aya(d:Date){const t=T(d),b=23*3600+51*60+25.5324,p=5029.0966*t+1.11161*t*t-.000113*t**3;return n360((b+p+nut(d).p)/3600)}
function node(d:Date){const t=T(d);return n360(125.04455501-1934.1361849*t+.0020762*t*t+t**3/467410-t**4/60616000)}
function asc(d:Date,lat:number,lon:number){const lst=n360(Astronomy.SiderealTime(d)*15+lon)*D,phi=lat*D,eps=(obl(d)+nut(d).e/3600)*D;return n360(Math.atan2(-Math.cos(lst),Math.sin(lst)*Math.cos(eps)+Math.tan(phi)*Math.sin(eps))*R+180)}
function rashi(l:number){const x=n360(l),i=Math.floor(x/30)%12;return{index:i,name:RASHIS[i],deg:x-i*30}}
function nak(l:number){const x=n360(l),i=Math.floor(x/NS)%27,w=x-i*NS;return{index:i,name:NAKSHATRAS[i],pada:Math.min(4,Math.floor(w/PS)+1),fraction:w/NS}}
function nav(l:number){const x=n360(l),s=Math.floor(x/30),part=Math.min(8,Math.floor((x-s*30)/(30/9))),m=s%3,start=m===0?s:m===1?(s+8)%12:(s+4)%12;return RASHIS[(start+part)%12]}
function trop(name:string,d:Date){if(name==='Rahu'||name==='Ketu'){const r=node(d);return name==='Rahu'?r:n360(r+180)}if(name==='Sun')return n360(Astronomy.SunPosition(d).elon);if(name==='Moon')return n360(Astronomy.EclipticGeoMoon(d).lon);const b:Record<string,Astronomy.Body>={Mercury:Astronomy.Body.Mercury,Venus:Astronomy.Body.Venus,Mars:Astronomy.Body.Mars,Jupiter:Astronomy.Body.Jupiter,Saturn:Astronomy.Body.Saturn};return n360(Astronomy.Ecliptic(Astronomy.GeoVector(b[name],d,true)).elon)}
function retro(n:string,d:Date){if(n==='Rahu'||n==='Ketu')return true;if(n==='Sun'||n==='Moon')return false;const h=21600000;return n180(trop(n,new Date(d.getTime()+h))-trop(n,new Date(d.getTime()-h)))<0}
function kar(i:number){if(i===0)return'Kimstughna';if(i>=57)return['Shakuni','Chatushpada','Naga'][i-57]??'Naga';return['Bava','Balava','Kaulava','Taitila','Garaja','Vanija','Vishti'][(i-1)%7]}
function dasha(b:Date,ni:number,nf:number){const lord=ORDER[ni%9],y=YEARS[lord],si=ORDER.indexOf(lord);let c=b.getTime()-y*nf*365.25*DAY;const periods:Array<{lord:string;startsAt:number;endsAt:number}>=[];for(let z=0;z<2;z++)for(let j=0;j<9;j++){const l=ORDER[(si+j)%9],e=c+YEARS[l]*365.25*DAY;periods.push({lord:l,startsAt:c,endsAt:e});c=e}const now=Date.now(),cur=periods.find(p=>p.startsAt<=now&&now<p.endsAt)??periods.find(p=>p.startsAt<=b.getTime()&&b.getTime()<p.endsAt)??periods[0];return{birthLord:lord,currentLord:cur.lord,currentEndsAt:cur.endsAt,periods}}
function instant(date:string,time:string,off:number){const dm=/^(\d{4})-(\d{2})-(\d{2})$/.exec(date.trim()),tm=/^(\d{2}):(\d{2})(?::(\d{2}))?$/.exec(time.trim());if(!dm||!tm)throw Error('Use YYYY-MM-DD and HH:MM.');const y=+dm[1],m=+dm[2]-1,da=+dm[3],h=+tm[1],mi=+tm[2],s=+(tm[3]||0);if(m<0||m>11||da<1||da>31||h>23||mi>59||s>59)throw Error('Birth date/time is invalid.');const x=new Date(Date.UTC(y,m,da,h,mi,s)-off*60000);if(Number.isNaN(x.getTime()))throw Error('Invalid birth instant.');return x}
export function calculateChart(date:string,time:string,lat:number,lon:number,off:number):Chart{if(!Number.isFinite(lat)||lat<-90||lat>90)throw Error('Latitude must be -90 to 90.');if(!Number.isFinite(lon)||lon<-180||lon>180)throw Error('Longitude must be -180 to 180.');if(!Number.isFinite(off)||off<-840||off>840)throw Error('UTC offset is invalid.');const b=instant(date,time,off),a=aya(b),al=n360(asc(b,lat,lon)-a),ar=rashi(al),an=nak(al),names=['Sun','Moon','Mercury','Venus','Mars','Jupiter','Saturn','Rahu','Ketu'];const planets=names.map(name=>{const sl=n360(trop(name,b)-a),rr=rashi(sl),nn=nak(sl);return{name,siderealLongitude:sl,rashi:rr.name,degreesInRashi:rr.deg,nakshatra:nn.name,pada:nn.pada,house:((rr.index-ar.index+12)%12)+1,navamsa:nav(sl),retrograde:retro(name,b)}});const sun=planets[0],moon=planets[1],el=n360(moon.siderealLongitude-sun.siderealLongitude),t0=Math.floor(el/12),tn=t0+1,pk=tn<=15?'Shukla':'Krishna',w=(tn-1)%15+1,ti=w===15?(pk==='Shukla'?'Purnima':'Amavasya'):TITHIS[w-1],mn=nak(moon.siderealLongitude),yi=Math.floor(n360(sun.siderealLongitude+moon.siderealLongitude)/NS)%27;return{engineVersion:'0.3.1-mobile',ephemeris:'Astronomy Engine 2.1.19',ayanamsa:'Lahiri / Indian Astronomical Ephemeris standard true ayanamsha',ayanamsaDegrees:a,utc:b.toISOString(),ascendant:{longitude:al,rashi:ar.name,degreesInRashi:ar.deg,nakshatra:an.name,pada:an.pada},planets,panchang:{tithiNumber:tn,tithi:ti,paksha:pk,nakshatra:mn.name,pada:mn.pada,yoga:YOGAS[yi],karana:kar(Math.floor(el/6))},dasha:dasha(b,mn.index,mn.fraction)}}
