import type {Chart} from './astrology';

export type GuidanceTopic='career'|'marriage'|'love'|'money'|'education'|'problems'|'business'|'travel'|'general';
export type Guidance={topic:GuidanceTopic;title:string;summary:string;why:string[];actions:string[];remedies:string[];confidence:string;disclaimer:string};

const careerWords=['job','career','government job','employment','ଚାକିରି','କ୍ୟାରିୟର','नौकरी','करियर'];
const marriageWords=['marriage','marry','wedding','ବିବାହ','ଶାଦି','शादी','विवाह'];
const loveWords=['love','girlfriend','boyfriend','breakup','ex','relationship','ପ୍ରେମ','ବ୍ରେକଅପ','प्यार','ब्रेकअप','रिलेशन'];
const moneyWords=['money','finance','loan','debt','wealth','ଟଙ୍କା','ଋଣ','पैसा','कर्ज'];
const educationWords=['study','exam','education','ପଢ଼ା','ପରୀକ୍ଷା','पढ़ाई','परीक्षा'];
const problemWords=['problem','why','trouble','bad time','କାହିଁକି','ସମସ୍ୟା','परेशानी','क्यों'];
const businessWords=['business','startup','व्यापार','ବ୍ୟବସାୟ'];
const travelWords=['foreign','abroad','travel','overseas','ବିଦେଶ','विदेश'];
const has=(s:string,ws:string[])=>ws.some(w=>s.includes(w));
export function detectTopic(q:string):GuidanceTopic{const s=q.toLowerCase();if(has(s,careerWords))return'career';if(has(s,marriageWords))return'marriage';if(has(s,loveWords))return'love';if(has(s,moneyWords))return'money';if(has(s,educationWords))return'education';if(has(s,businessWords))return'business';if(has(s,travelWords))return'travel';if(has(s,problemWords))return'problems';return'general'}

const benefics=new Set(['Jupiter','Venus','Mercury','Moon']);
function p(chart:Chart,name:string){return chart.planets.find(x=>x.name===name)}
function planetsIn(chart:Chart,houses:number[]){return chart.planets.filter(x=>houses.includes(x.house))}
function score(chart:Chart,houses:number[],lords:string[]){let s=50;for(const x of planetsIn(chart,houses))s+=benefics.has(x.name)?8:-4;if(lords.includes(chart.dasha.currentLord))s+=18;const j=p(chart,'Jupiter');if(j&&houses.includes(j.house))s+=10;return Math.max(20,Math.min(90,s))}
function band(s:number){return s>=72?'strong':s>=55?'moderate':'mixed'}
function confidence(chart:Chart){const data=chart.utc&&chart.ascendant&&chart.planets.length>=9;return data?'High calculation-data confidence when the entered birth time and coordinates are accurate. Prediction certainty remains limited because astrology is a traditional interpretive system.':'Birth data needs review before relying on this analysis.'}

export function analyseQuestion(chart:Chart,question:string):Guidance{
 const topic=detectTopic(question);let s=50,title='Life Guidance',summary='',houses:number[]=[1,5,9],lords:string[]=[];let actions:string[]=[];let remedies:string[]=[];
 if(topic==='career'){title='Job & Career Guidance';houses=[2,6,10,11];lords=['Saturn','Mercury','Jupiter','Sun'];s=score(chart,houses,lords);summary=`Your current career indicators look ${band(s)}. The running ${chart.dasha.currentLord} Mahadasha is the main timing factor in this reading.`;actions=['Keep applications and interview preparation active rather than waiting for a single predicted date.','Prioritize periods when opportunities actually appear and document applications weekly.','Use the chart as timing guidance, not as a replacement for skill-building or career advice.'];remedies=['Offer practical seva or charity on Saturdays when Saturn-type delay is a concern.','A simple daily prayer or mantra practice is safer than expensive ritual promises.','For career focus, maintain disciplined morning study/work routines.']}
 else if(topic==='marriage'){title='Marriage Guidance';houses=[2,7,11];lords=['Venus','Jupiter','Moon'];s=score(chart,houses,lords);summary=`Marriage-related indicators are ${band(s)} in this traditional reading. The 7th-house pattern and ${chart.dasha.currentLord} Mahadasha should be considered together rather than using one planet alone.`;actions=['Treat timing as a window, not a guaranteed wedding date.','Use compatibility, communication and family expectations alongside astrology.','If birth time is uncertain, avoid narrow month-level predictions.'];remedies=['Friday prayer/charity may be used as a gentle Venus-oriented traditional practice.','Respectful family/relationship communication is more important than costly rituals.','Avoid gemstones unless assessed carefully by a qualified practitioner.']}
 else if(topic==='love'){title='Love & Relationship Guidance';houses=[5,7,11];lords=['Venus','Moon','Jupiter'];s=score(chart,houses,lords);summary=`Relationship indicators are ${band(s)}. Astrology cannot know another person's private intentions, so this does not guarantee that a specific ex-partner will return.`;actions=['If reconciliation is possible, look for real communication and consent instead of relying only on prediction.','Use the reading to understand your emotional timing and patterns.','Do not repeatedly contact someone who has asked for distance.'];remedies=['Friday gratitude/prayer and acts of kindness are low-risk traditional practices.','Work on emotional steadiness, sleep and communication habits.','Avoid rituals claiming to control or force another person.']}
 else if(topic==='money'){title='Money & Finance Guidance';houses=[2,5,8,11];lords=['Jupiter','Venus','Mercury'];s=score(chart,houses,lords);summary=`Financial indicators look ${band(s)}. This is traditional timing guidance, not investment advice.`;actions=['Keep an emergency fund and track debt independently of astrology.','Treat favourable periods as a reason for disciplined planning, not high-risk speculation.','Use a licensed financial professional for major investments or loans.'];remedies=['Thursday charity or educational donation is a gentle Jupiter-oriented tradition.','Avoid expensive puja or gemstones sold with guaranteed wealth claims.','Practice regular budgeting as the primary practical remedy.']}
 else if(topic==='education'){title='Education & Exam Guidance';houses=[4,5,9];lords=['Mercury','Jupiter','Moon'];s=score(chart,houses,lords);summary=`Education indicators are ${band(s)}, with ${chart.dasha.currentLord} Mahadasha influencing concentration and timing.`;actions=['Use a fixed revision timetable and mock tests.','Track weak subjects weekly rather than changing strategy frequently.','Treat astrology only as motivational timing support.'];remedies=['A brief morning Saraswati prayer/mantra may be used if meaningful to you.','Donate books or support education as a traditional positive practice.','Sleep and structured revision remain the strongest practical actions.']}
 else if(topic==='business'){title='Business Guidance';houses=[2,7,10,11];lords=['Mercury','Jupiter','Saturn'];s=score(chart,houses,lords);summary=`Business indicators are ${band(s)} in this chart pattern.`;actions=['Validate demand, cash flow and legal requirements before committing money.','Avoid taking business risk only because a period looks favourable.','Use professional tax/legal advice where required.'];remedies=['Wednesday learning/skill practice can be used as a Mercury-oriented tradition.','Charity and honest dealing are safer than costly prosperity rituals.']}
 else if(topic==='travel'){title='Foreign Travel Guidance';houses=[3,9,12];lords=['Rahu','Jupiter','Mercury'];s=score(chart,houses,lords);summary=`Travel/foreign-location indicators are ${band(s)}. Actual visas, admission, employment and finances remain decisive.`;actions=['Prepare documentation early.','Check visa and financial eligibility from official sources.','Use timing windows only to prioritize applications.'];remedies=['Thursday prayer/charity may be used as a traditional Jupiter-oriented practice.','Avoid paying anyone who guarantees visa success through astrology.']}
 else {title=topic==='problems'?'Why Am I Facing Problems?':'Personal Vedic Guidance';houses=[1,4,8,9,12];lords=['Saturn','Rahu','Ketu'];s=score(chart,houses,lords);summary=`The overall pattern is ${band(s)}. Your running ${chart.dasha.currentLord} Mahadasha is an important background influence, but real-life causes should also be investigated directly.`;actions=['Separate practical causes—health, work, money, relationships—from astrological interpretation.','Address urgent medical, legal or financial issues with qualified professionals.','Use the chart to support reflection, not fear.'];remedies=['Simple prayer, meditation, charity and disciplined routines are preferred over fear-based expensive remedies.','If a specific puja is suggested later, AstroSathi should explain the exact traditional rule behind it.']}
 const why=[`Current Mahadasha: ${chart.dasha.currentLord}.`,`Relevant houses analysed: ${houses.join(', ')}.`,...planetsIn(chart,houses).slice(0,4).map(x=>`${x.name} is placed in house ${x.house} in ${x.rashi}${x.retrograde?' (retrograde)':''}.`),`Lagna: ${chart.ascendant.rashi}; Moon Nakshatra: ${chart.panchang.nakshatra}.`];
 return{topic,title,summary,why,actions,remedies,confidence:confidence(chart),disclaimer:'Traditional Vedic astrology is not scientifically established. Results are guidance, not guarantees. Never substitute them for medical, legal, financial or mental-health professionals.'};
}
