import type {GuidanceTopic} from './guidance';

export type LocalIntent='timing'|'current'|'cause'|'remedy'|'likelihood'|'comparison'|'profile'|'forecast'|'advice';
export type LocalFocus='none'|'intimacy'|'partner'|'jobType'|'marriageType'|'businessVsJob'|'studyAbroad'|'debt'|'reconciliation';
export type LocalContext={topic:GuidanceTopic;intent:LocalIntent;focus:LocalFocus};
export type LocalUnderstanding={topic:GuidanceTopic;intent:LocalIntent;focus:LocalFocus;topicConfidence:number;intentConfidence:number;focusConfidence:number};

type Example={text:string;topic:GuidanceTopic;intent:LocalIntent;focus:LocalFocus};
const E:Example[]=[
 ['when will i get a job','career','timing','none'],['government or private job which is better','career','comparison','jobType'],['why is my career delayed','career','cause','none'],['what should i do for promotion','career','advice','none'],['how is my job situation now','career','current','none'],['will i get selected in interview','career','likelihood','none'],['job or business for me','career','comparison','businessVsJob'],['naukri kab milegi','career','timing','none'],['sarkari ya private naukri','career','comparison','jobType'],['meri naukri kyu delay hai','career','cause','none'],['मुझे नौकरी कब मिलेगी','career','timing','none'],['सरकारी या प्राइवेट नौकरी','career','comparison','jobType'],['मेरे करियर में देरी क्यों है','career','cause','none'],['ଚାକିରି କେବେ ମିଳିବ','career','timing','none'],['ସରକାରୀ କି ପ୍ରାଇଭେଟ ଚାକିରି','career','comparison','jobType'],['ମୋ କ୍ୟାରିୟରରେ ବିଳମ୍ବ କାହିଁକି','career','cause','none'],
 ['when will i marry','marriage','timing','none'],['love marriage or arranged marriage','marriage','comparison','marriageType'],['what kind of spouse will i have','marriage','profile','partner'],['why is marriage delayed','marriage','cause','none'],['is marriage possible this year','marriage','likelihood','none'],['shaadi kab hogi','marriage','timing','none'],['love marriage ya arranged','marriage','comparison','marriageType'],['meri wife kaisi hogi','marriage','profile','partner'],['मेरी शादी कब होगी','marriage','timing','none'],['लव मैरिज या अरेंज मैरिज','marriage','comparison','marriageType'],['जीवनसाथी कैसा होगा','marriage','profile','partner'],['ବିବାହ କେବେ ହେବ','marriage','timing','none'],['ପ୍ରେମ ବିବାହ କି ଆରେଞ୍ଜ ବିବାହ','marriage','comparison','marriageType'],['ଜୀବନସାଥୀ କେମିତି ହେବେ','marriage','profile','partner'],
 ['how is my love life','love','forecast','none'],['will my relationship improve','love','likelihood','none'],['will my ex come back','love','likelihood','reconciliation'],['kiss','love','current','intimacy'],['kissing','love','current','intimacy'],['physical intimacy','love','current','intimacy'],['sex','love','current','intimacy'],['sexual relationship','love','forecast','intimacy'],['intimacy with partner','love','current','intimacy'],['romantic physical relation','love','forecast','intimacy'],['hug kiss romance','love','current','intimacy'],['breakup patch up','love','likelihood','reconciliation'],['pyar kaisa rahega','love','forecast','none'],['ex wapas aayega','love','likelihood','reconciliation'],['kiss kab hoga','love','timing','intimacy'],['सेक्स लाइफ कैसी रहेगी','love','forecast','intimacy'],['किस और अंतरंग संबंध','love','current','intimacy'],['मेरा एक्स वापस आएगा','love','likelihood','reconciliation'],['प्यार कब मिलेगा','love','timing','none'],['ଚୁମ୍ବନ ଓ ଅନ୍ତରଙ୍ଗ ସମ୍ପର୍କ','love','current','intimacy'],['ଯୌନ ସମ୍ପର୍କ କେମିତି ରହିବ','love','forecast','intimacy'],['ପୂର୍ବ ସାଥୀ ପୁଣି ଫେରିବେ କି','love','likelihood','reconciliation'],['ପ୍ରେମ କେବେ ମିଳିବ','love','timing','none'],
 ['when will money improve','money','timing','none'],['why do i have money problems','money','cause','none'],['when will loan end','money','timing','debt'],['how is income now','money','current','none'],['should i take a loan','money','advice','debt'],['paisa kab ayega','money','timing','none'],['karz kab khatam hoga','money','timing','debt'],['पैसा कब आएगा','money','timing','none'],['कर्ज कब खत्म होगा','money','timing','debt'],['ଟଙ୍କା କେବେ ଭଲ ହେବ','money','timing','none'],['ଋଣ କେବେ ଶେଷ ହେବ','money','timing','debt'],
 ['when is my best exam period','education','timing','none'],['why can i not concentrate','education','cause','none'],['will i pass exam','education','likelihood','none'],['study abroad or india','education','comparison','studyAbroad'],['how is my study now','education','current','none'],['exam kab acha rahega','education','timing','none'],['विदेश में पढ़ाई होगी','education','likelihood','studyAbroad'],['परीक्षा का अच्छा समय कब है','education','timing','none'],['ବିଦେଶରେ ପଢ଼ିବି କି','education','likelihood','studyAbroad'],['ପରୀକ୍ଷା ପାଇଁ ଭଲ ସମୟ କେବେ','education','timing','none'],
 ['why am i facing obstacles','problems','cause','none'],['when will bad time end','problems','timing','none'],['what remedy for obstacles','problems','remedy','none'],['why everything is going wrong','problems','cause','none'],['समस्या क्यों आ रही है','problems','cause','none'],['बुरा समय कब खत्म होगा','problems','timing','none'],['ସମସ୍ୟା କାହିଁକି ଆସୁଛି','problems','cause','none'],['ଖରାପ ସମୟ କେବେ ଶେଷ ହେବ','problems','timing','none'],
 ['business or job','business','comparison','businessVsJob'],['when will business grow','business','timing','none'],['should i start business','business','advice','none'],['why business loss','business','cause','none'],['बिजनेस या नौकरी','business','comparison','businessVsJob'],['व्यापार कब बढ़ेगा','business','timing','none'],['ବ୍ୟବସାୟ କି ଚାକିରି','business','comparison','businessVsJob'],['ବ୍ୟବସାୟ କେବେ ବଢ଼ିବ','business','timing','none'],
 ['when will i go abroad','travel','timing','none'],['will visa get approved','travel','likelihood','none'],['foreign travel possible','travel','likelihood','none'],['study abroad','travel','forecast','studyAbroad'],['videsh kab jaunga','travel','timing','none'],['विदेश कब जाऊंगा','travel','timing','none'],['ବିଦେଶ କେବେ ଯିବି','travel','timing','none'],
 ['when will we have a child','children','timing','none'],['children in my chart','children','forecast','none'],['संतान कब होगी','children','timing','none'],['ସନ୍ତାନ କେବେ ହେବ','children','timing','none'],
 ['when to buy house','property','timing','none'],['property purchase good now','property','current','none'],['घर कब खरीदूं','property','timing','none'],['ଘର କେବେ କିଣିବି','property','timing','none'],
 ['why family tension','family','cause','none'],['how is family life','family','forecast','none'],['परिवार में तनाव क्यों','family','cause','none'],['ପରିବାରରେ ତଣାପୋଡ଼ କାହିଁକି','family','cause','none'],
 ['how is my health period','health','forecast','none'],['why health feels weak','health','cause','none'],['स्वास्थ्य कैसा रहेगा','health','forecast','none'],['ସ୍ୱାସ୍ଥ୍ୟ କେମିତି ରହିବ','health','forecast','none'],
 ['what puja should i do','spiritual','remedy','none'],['which mantra now','spiritual','remedy','none'],['पूजा या उपाय क्या करूं','spiritual','remedy','none'],['କେଉଁ ପୂଜା କରିବି','spiritual','remedy','none'],
 ['what is strongest in my life','general','current','none'],['tell me my future','general','forecast','none'],['what should i do now','general','advice','none'],['मेरा भविष्य बताइए','general','forecast','none'],['ଏବେ ମୋ ଜୀବନରେ କଣ ଶକ୍ତିଶାଳୀ','general','current','none']
];

const DIM=512;
const TOPICS:Array<GuidanceTopic>=['career','marriage','love','money','education','problems','business','travel','children','property','family','health','spiritual','general'];
const INTENTS:Array<LocalIntent>=['timing','current','cause','remedy','likelihood','comparison','profile','forecast','advice'];
const FOCI:Array<LocalFocus>=['intimacy','partner','jobType','marriageType','businessVsJob','studyAbroad','debt','reconciliation'];

function norm(s:string){return s.normalize('NFKC').toLowerCase().replace(/[\u200b-\u200d\ufeff]/g,'').replace(/[^\p{L}\p{N}\s]+/gu,' ').replace(/\s+/g,' ').trim()}
function hash(s:string){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function vec(text:string){const s=norm(text),v=new Float32Array(DIM);if(!s)return v;const words=s.split(' ');const add=(f:string,w:number)=>{const h=hash(f);v[h%DIM]+=((h&1)?1:-1)*w};for(const w of words){if(!w)continue;add('w:'+w,1.8);const x='^'+w+'$';for(let n=2;n<=4;n++)for(let i=0;i+n<=x.length;i++)add(`c${n}:`+x.slice(i,i+n),n===2?.35:n===3?.7:.45)}for(let i=0;i<words.length-1;i++)add('b:'+words[i]+'_'+words[i+1],1.15);let z=0;for(const x of v)z+=x*x;z=Math.sqrt(z)||1;for(let i=0;i<v.length;i++)v[i]/=z;return v}
function normalize(v:Float32Array){let z=0;for(const x of v)z+=x*x;z=Math.sqrt(z)||1;for(let i=0;i<v.length;i++)v[i]/=z;return v}
function dot(a:Float32Array,b:Float32Array){let s=0;for(let i=0;i<DIM;i++)s+=a[i]*b[i];return s}

type CentroidMap<T extends string>=Record<T,Float32Array>;
let topicC:CentroidMap<GuidanceTopic>|undefined,intentC:CentroidMap<LocalIntent>|undefined,focusC:Partial<Record<LocalFocus,Float32Array>>|undefined;
function build(){if(topicC)return;topicC=Object.fromEntries(TOPICS.map(x=>[x,new Float32Array(DIM)])) as CentroidMap<GuidanceTopic>;intentC=Object.fromEntries(INTENTS.map(x=>[x,new Float32Array(DIM)])) as CentroidMap<LocalIntent>;focusC={};for(const f of FOCI)focusC[f]=new Float32Array(DIM);const countsT:Record<string,number>={},countsI:Record<string,number>={},countsF:Record<string,number>={};for(const e of E){const x=vec(e.text);for(let i=0;i<DIM;i++){topicC[e.topic][i]+=x[i];intentC![e.intent][i]+=x[i];if(e.focus!=='none')focusC[e.focus]![i]+=x[i]}countsT[e.topic]=(countsT[e.topic]||0)+1;countsI[e.intent]=(countsI[e.intent]||0)+1;if(e.focus!=='none')countsF[e.focus]=(countsF[e.focus]||0)+1}for(const t of TOPICS)normalize(topicC[t]);for(const i of INTENTS)normalize(intentC![i]);for(const f of FOCI)normalize(focusC[f]!)}
function best<T extends string>(q:Float32Array,labels:T[],m:Record<T,Float32Array>){let label=labels[0],score=-2,second=-2;for(const x of labels){const s=dot(q,m[x]);if(s>score){second=score;score=s;label=x}else if(s>second)second=s}return{label,score,margin:score-second}}

export function understandLocal(question:string,previous?:LocalContext):LocalUnderstanding{
 build();const q=vec(question);const t=best(q,TOPICS,topicC!),i=best(q,INTENTS,intentC!);const fm=focusC as Record<LocalFocus,Float32Array>,f=best(q,FOCI,fm);const wordCount=norm(question).split(' ').filter(Boolean).length;
 let topic=t.label,intent=i.label,focus:LocalFocus=f.score>=.22?f.label:'none';
 if(previous&&wordCount<=7&&t.score<.28)topic=previous.topic;
 if(previous&&wordCount<=5&&i.score<.23)intent=previous.intent;
 if(previous&&wordCount<=4&&focus==='none'&&previous.focus!=='none')focus=previous.focus;
 // Very short affection terms need a strong semantic anchor rather than a generic fallback.
 if(/^(kiss|kissing|hug|romance|सेक्स|किस|ଚୁମ୍ବନ|ଯୌନ)$/iu.test(norm(question))){topic='love';focus='intimacy';if(intent==='forecast')intent='current'}
 if(/\b(ex|former partner)\b|एक्स|ପୂର୍ବ ସାଥୀ/iu.test(norm(question))) {topic='love';focus='reconciliation'}
 return{topic,intent,focus,topicConfidence:Math.max(0,Math.min(1,t.score+.25*t.margin)),intentConfidence:Math.max(0,Math.min(1,i.score+.25*i.margin)),focusConfidence:focus==='none'?1-Math.max(0,f.score):Math.max(0,Math.min(1,f.score+.25*f.margin))};
}

export const LOCAL_AI_MODEL_INFO={name:'Jyotish G Compact Semantic Model',version:'1.0.0',architecture:'hashed character/word n-gram nearest-centroid classifier',dimensions:DIM,trainingExamples:E.length,networkRequired:false,paidApiRequired:false} as const;
